spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Para rutas que empiezan con /auth-service/
        - id: auth-service-routes
          uri: lb://AUTH-SERVICE # Este debe ser el nombre EXACTO que aparece en Eureka
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1  # Remueve /auth-service del path
            
        # Para rutas que empiezan con /catalog-service/  
        - id: catalog-service-routes
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: TuClaveSecretaMasSeguraYDeLongitudAdecuadaParaHS512

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.server: DEBUG
    org.springframework.cloud.client.discovery: DEBUG
