# spring:
#   application:
#     name: gateway-service
#   cloud:
#     gateway:
#       discovery:
#         locator:
#           enabled: true
#           lower-case-service-id: true
#       routes:
#         - id: auth-service
#           uri: lb://auth-service
#           predicates:
#             - Path=/auth/**
#           filters:
#             - StripPrefix=1
#         - id: other-services
#           uri: lb://catalog-service
#           predicates:
#             - Path=/catalog/**
#           filters:
#             - StripPrefix=1


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE  # Usa el nombre EXACTO que aparece en Eureka
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,INTERNAL_SERVER_ERROR

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: TuClaveSecretaMasSeguraYDeLongitudAdecuadaParaHS512

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.server: DEBUG
